title: Running batch operations on files
hero_image: images/banner.png
description: bash-batch-operations-on-files description
description: How to run batch operations on files using bash
original_url:
theme: cc-prototype
listed: false
steps:
  - title: Batch file operations

